require("DBI")
con = dbConnect(duckdb::duckdb(), ":ldbc:")

invisible(dbExecute(con,"DROP TABLE IF exists Raw_Organisation"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Place"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_TagClass"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Comment"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Comment_hasTag_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Forum"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Forum_hasMember_Person"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Forum_hasTag_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_hasInterest_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_knows_Person"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_knows_Person"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_likes_Post"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_likes_Comment"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_studyAt_University"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Person_workAt_Company"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Post"))
invisible(dbExecute(con,"DROP TABLE IF exists Raw_Post_hasTag_Tag"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Message"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Undirected_edges"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS person_degree"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS forum_degree"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS post_degree"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS comment_degree"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS city_degree"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS tag_degree"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Comment_replyOf_Message"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Message_hasCreator_Person"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Message_hasTag_Tag"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Message_isLocatedIn_Country"))
invisible(dbExecute(con,"DROP VIEW IF EXISTS Person_likes_Message"))
invisible(dbExecute(con,"DROP TABLE IF exists Company"))
invisible(dbExecute(con,"DROP TABLE IF exists University"))
invisible(dbExecute(con,"DROP TABLE IF exists Continent"))
invisible(dbExecute(con,"DROP TABLE IF exists Country"))
invisible(dbExecute(con,"DROP TABLE IF exists City"))
invisible(dbExecute(con,"DROP TABLE IF exists Place"))
invisible(dbExecute(con,"DROP TABLE IF exists Organisation"))
invisible(dbExecute(con,"DROP TABLE IF exists Forum"))
invisible(dbExecute(con,"DROP TABLE IF exists Comment"))
invisible(dbExecute(con,"DROP TABLE IF exists Post"))
invisible(dbExecute(con,"DROP TABLE IF exists Person"))
invisible(dbExecute(con,"DROP TABLE IF exists Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists TagClass"))
invisible(dbExecute(con,"DROP TABLE IF exists Comment_hasTag_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Post_hasTag_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Forum_hasMember_Person"))
invisible(dbExecute(con,"DROP TABLE IF exists Forum_hasTag_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Person_hasInterest_Tag"))
invisible(dbExecute(con,"DROP TABLE IF exists Person_likes_Comment"))
invisible(dbExecute(con,"DROP TABLE IF exists Person_likes_Post"))
invisible(dbExecute(con,"DROP TABLE IF exists Person_studyAt_University"))
invisible(dbExecute(con,"DROP TABLE IF exists Person_workAt_Company"))
invisible(dbExecute(con,"DROP TABLE IF exists Person_knows_Person"))



