library("DBI")
con = dbConnect(duckdb::duckdb(), ":ldbc:")
invisible(dbExecute(con, "INSERT INTO Organisation SELECT * FROM Raw_Organisation"))
invisible(dbExecute(con, "INSERT INTO Place SELECT * FROM Raw_Place"))
invisible(dbExecute(con, "INSERT INTO Tag SELECT * FROM Raw_Tag"))
invisible(dbExecute(con, "INSERT INTO TagClass SELECT * FROM Raw_TagClass"))
invisible(dbExecute(con, "INSERT INTO Company SELECT id, name, url, isLocatedIn_Place AS isLocatedIn_Country FROM Organisation WHERE type = 'Company'"))
invisible(dbExecute(con, "INSERT INTO University SELECT id, name, url, isLocatedIn_Place AS isLocatedIn_City FROM Organisation WHERE type = 'University'"))
invisible(dbExecute(con, "INSERT INTO Continent SELECT id, name, url FROM Place WHERE type = 'Continent'"))
invisible(dbExecute(con, "INSERT INTO Country SELECT id, name, url, isPartOf_Place AS isPartOf_Continent FROM Place WHERE type = 'Country'"))
invisible(dbExecute(con, "INSERT INTO City  SELECT id, name, url, isPartOf_Place AS isPartOf_Country FROM Place WHERE type = 'City'"))
invisible(dbExecute(con, "INSERT INTO Comment_hasTag_Tag SELECT  id, hasTag_Tag FROM Raw_Comment_hasTag_Tag"))
invisible(dbExecute(con, "INSERT INTO Post_hasTag_Tag SELECT  id, hasTag_Tag FROM Raw_Post_hasTag_Tag"))
invisible(dbExecute(con, "INSERT INTO Forum_hasMember_Person SELECT  id, hasMember_Person FROM Raw_Forum_hasMember_Person"))
invisible(dbExecute(con, "INSERT INTO Forum_hasTag_Tag SELECT  id, hasTag_Tag FROM Raw_Forum_hasTag_Tag"))
invisible(dbExecute(con, "INSERT INTO Person_hasInterest_Tag SELECT  id, hasInterest_Tag FROM Raw_Person_hasInterest_Tag"))
invisible(dbExecute(con, "INSERT INTO Person_likes_Comment SELECT  id, likes_Comment FROM Raw_Person_likes_Comment"))
invisible(dbExecute(con, "INSERT INTO Person_likes_Post SELECT  id, likes_Post FROM Raw_Person_likes_Post"))
invisible(dbExecute(con, "INSERT INTO Person_studyAt_University SELECT  id, studyAt_University, classYear FROM Raw_Person_studyAt_University"))
invisible(dbExecute(con, "INSERT INTO Person_workAt_Company SELECT  id, workAt_Company, workFrom FROM Raw_Person_workAt_Company"))
invisible(dbExecute(con, "INSERT INTO Person_knows_Person SELECT  Person1id, Person2id FROM Raw_Person_knows_Person"))
invisible(dbExecute(con, "INSERT INTO Comment SELECT id, content, hasCreator_Person, isLocatedIn_Country, replyOf_Post, replyOf_Comment FROM Raw_Comment"))
invisible(dbExecute(con, "INSERT INTO Forum SELECT id, title, hasModerator_Person FROM Raw_Forum"))
invisible(dbExecute(con, "INSERT INTO Post SELECT id, content, hasCreator_Person, Forum_containerOf, isLocatedIn_Country FROM Raw_Post"))
invisible(dbExecute(con, "INSERT INTO Person SELECT id, firstName, lastName, isLocatedIn_City FROM Raw_Person"))
